### ISSUE TITLE
ExportParams is not defined

### ISSUE THREAD

**Issue by schlami** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#222] opened 2024-09-24 10:04 UTC
### Current Behavior

I installed version 7.0.0/7.0.1 and it doesn't work at all for me. Probably I'm doing something wrong, so please help me. When I press the "Export to PDF" button, nothing happens. 
In the main log I see the following error:
`2024-09-24 14:18:06,190 [ajp-nio-127.0.0.1-8889-exec-6 | u:admin] INFO  com.polarion.reina.web.internal.server.ria.ServerLogger - 2024-8-24 14:18:5.163  ERROR: Uncaught ReferenceError: ExportParams is not defined
line: 127`

 With Chrome Inspector I can see the following request payload: 
`7|2|8|http://polariontmp/polarion/gwt/com.polarion.UI/|6D25EB1D6078689C62FB7503EBB617B9|com.google.gwt.user.client.rpc.XsrfToken/4254043109|jtK8TQa3UxEVTc7de4OhhPV8YR3PJW0f|com.polarion.alm.ui.client.debug.DebugService|debug|[Ljava.lang.String;/2600011424|2024-8-24 11:53:10.353  ERROR: Uncaught ReferenceError: ExportParams is not defined 
line: 127 
url: http://polariontmp/polarion/pdf-exporter/ui/js/export-pdf.js?timestamp=1727171212897|1|2|3|4|5|6|1|7|7|1|8|`

I'm not sure whether this is related to the problem above, but in Swagger POST /api/convert/jobs the export parameters changed:
"projectId" to  "Project ID",
"locationPath" to  "Location path"
Swagger is complaining about the new export parameters. 

### Expected Behavior

see above

### Steps To Reproduce

see above

### Environment - OS

Linux

### Polarion version

2404

### Extension Version

7.0.0

**Comment by grigoriev** [comment] 2024-09-24 12:39
@schlami,
unfortunately, we were not able to reproduce it.
Could you please try clear you browser cache first?

And please provide us with the information from About page and content of `/polarion/#/administration/properties`

**Comment by grigoriev** [comment] 2024-09-24 13:35
@schlami,
thank you, we have reproduced.
Will be fixed in v7.1.1 asap.

**Closed** 2024-09-24 13:39 UTC
Labels: bug

**Comment by grigoriev** [comment] 2024-09-24 13:46
@schlami,
could you please test with v7.1.1 and share the results?
